### ISSUE TITLE
provide some informations

### ISSUE THREAD

**Issue by e-bits** [dbrgn/collectd-python-plugins#2]
Hi,

can you please provide some more information how you are running `collectd`? Is it running on the raspberry pi itself? Is collectd installed locally or is it a docker container? which one?

I also plan to monitor my raspberry pi based lora gateway with prometheus and grafana.

Thanks for your help
Regards e-bits

**Comment by dbrgn** [comment]
Hi. I simply installed collectd on the Raspberry Pi from the regular Debian repositories. It sends data to an InfluxDB instance, I never used Prometheus so far. You should be able to find tutorials about this configuration online.

If you need more information, feel free to comment.
