### ISSUE TITLE
Question about using multiple scripts in collectd-python

### ISSUE THREAD

**Issue by dhuseljic** [dbrgn/collectd-python-plugins#5]
Hello,

thank you for sharing your work, it was really helpful.
I have a question you might be able to answer (I did not find anything useful anywhere):

Do you know if it is possible to run multiple python files, which collectd uses for collecting data?

E.g., Let's say we have two python files like `temp.py` and `cpu.py`, and we want to have a config that looks like this: 
```
LoadPlugin python
<Plugin python>
    ModulePath "/opt/collectd_plugins"
    Import "cpu"
    Import "temp"
</Plugin>
```
With each file collecting data.
However, if I try this, only one of the scripts seems to be active. I was not able to run both scripts successfully.

I also tried different setups, such as having two of these plugin configurations, but I read that you should only define one `python.conf`. Having one `main.py` file with multiple `register_read`s is not working either.

Thanks for your help.

**Comment by dbrgn** [comment]
I think having multiple "Plugin" blocks should work:

```xml
LoadPlugin python
<Plugin python>
    ModulePath "/opt/collectd_plugins"
    Import "cpu"
</Plugin>
<Plugin python>
    ModulePath "/opt/collectd_plugins"
    Import "temp"
</Plugin>
```

But I'm not 100% sure about this. You will have to try it yourself.
